name: FFARush
version: 1.1.0
description: FFARush mini-game plugin.
author: Paulao17
authors: [Paulao17] 
website: yocraft.net/Plugins/
main: net.yocraft.ffarush.Main
commands:
  ffarush:
    description: Base command for the plugin.
    usage: /ffarush [args]